# Generated by Django 2.1.2 on 2018-10-21 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitnote',
            name='company',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='debit_notes', to='register.Company'),
            preserve_default=False,
        ),
    ]
