# Generated by Django 2.1.2 on 2018-10-25 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20181021_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('pending_customer', 'Pending Customer'), ('pending_company', 'Pending Company'), ('closed', 'Closed'), ('service_order', 'Service Order')], db_index=True, editable=False, max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_changed', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='transactions.Event')),
            ],
        ),
    ]
