# Generated by Django 2.1.2 on 2018-10-21 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_datafile'),
        ('transactions', '0002_serviceorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_changed', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='register.Category')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='register.Machine')),
            ],
        ),
    ]
