# Generated by Django 2.1.2 on 2018-10-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('transactions', '0003_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='files',
            field=models.ManyToManyField(related_name='requests', to='files.DataFile'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pictures',
            field=models.ManyToManyField(related_name='events', to='files.Picture'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='pictures',
            field=models.ManyToManyField(related_name='service_orders', to='files.Picture'),
        ),
    ]
