# Generated by Django 2.1.2 on 2018-10-20 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='address',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='cell_phone_number',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='home_phone_number',
        ),
        migrations.AddField(
            model_name='worker',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
