# Generated by Django 2.1.2 on 2018-10-22 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20181021_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='maincompany',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='register/maincompany/logo'),
        ),
        migrations.AlterField(
            model_name='maincompany',
            name='logo_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='register/maincompany/logothumb'),
        ),
    ]
