# Generated by Django 2.1.2 on 2018-10-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20181022_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ibge_code', models.CharField(db_index=True, editable=False, max_length=100, unique=True)),
                ('name', models.CharField(db_index=True, editable=False, max_length=100)),
                ('state_code', models.CharField(db_index=True, editable=False, max_length=2)),
                ('state', models.CharField(editable=False, max_length=100)),
                ('SIC', models.CharField(editable=False, max_length=100)),
                ('SCI', models.CharField(editable=False, max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_changed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'cities',
                'ordering': ('state_code', 'name'),
            },
        ),
    ]
