# Generated by Django 2.1.2 on 2018-10-24 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_user_woeid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'addresses'},
        ),
        migrations.RemoveField(
            model_name='message',
            name='title',
        ),
    ]
