# Generated by Django 2.1.2 on 2018-10-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20181024_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maincompany',
            name='address',
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='register/company/logo'),
        ),
        migrations.AddField(
            model_name='company',
            name='logo_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='register/company/logothumb'),
        ),
        migrations.AddField(
            model_name='company',
            name='main_company',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='MainCompany',
        ),
    ]
