# Generated by Django 2.1.2 on 2018-10-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20181024_2325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('id',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('id',), 'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(db_index=True),
        ),
    ]
