# Generated by Django 2.1.2 on 2018-11-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20181024_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture_profile',
            field=models.ImageField(blank=True, null=True, upload_to='register/user/picture-profile/'),
        ),
    ]
